# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Wed Aug 11 22:23:17 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class CVEFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CVEFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((825, 578))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_OPEN, "Open Project", "")
        self.Bind(wx.EVT_MENU, self.open_project, id=wx.ID_OPEN)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Load Image", "")
        self.Bind(wx.EVT_MENU, self.load_image, id=item.GetId())
        wxglade_tmp_menu.Append(wx.ID_SAVE, "Save project", "")
        self.Bind(wx.EVT_MENU, self.save_project, id=wx.ID_SAVE)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "Save project as", "")
        self.Bind(wx.EVT_MENU, self.save_project_as, id=wx.ID_SAVEAS)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Export Script", "")
        self.Bind(wx.EVT_MENU, self.export_script, id=item.GetId())
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "Exit", "")
        self.Bind(wx.EVT_MENU, self.exit, id=wx.ID_EXIT)
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.intro_pane = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.panel_2 = wx.ScrolledWindow(self.intro_pane, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_1 = wx.ScrolledWindow(self.intro_pane, wx.ID_ANY, style=wx.TAB_TRAVERSAL)

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CVEFrame.__set_properties
        self.SetTitle("frame")
        self.panel_2.SetScrollRate(10, 10)
        self.panel_1.SetMinSize((200, -1))
        self.panel_1.SetScrollRate(10, 10)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CVEFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 0)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, "Welcome to CVExplorer. Start by loading a sample image")
        label_1.Wrap(600)
        sizer_4.Add(label_1, 0, wx.ALL | wx.EXPAND, 3)
        self.panel_2.SetSizer(sizer_4)
        sizer_2.Add(self.panel_2, 1, wx.ALL | wx.EXPAND, 3)
        static_line_1 = wx.StaticLine(self.intro_pane, wx.ID_ANY, style=wx.LI_VERTICAL)
        sizer_2.Add(static_line_1, 0, wx.EXPAND, 0)
        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "label_4")
        grid_sizer_1.Add(label_4, 0, wx.ALL, 3)
        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Params")
        grid_sizer_1.Add(label_5, 0, wx.ALL, 3)
        sizer_3.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_3.Add(static_line_2, 0, wx.EXPAND, 0)
        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Result params")
        label_3.SetMinSize((120, 300))
        sizer_3.Add(label_3, 0, wx.ALL, 3)
        self.panel_1.SetSizer(sizer_3)
        sizer_2.Add(self.panel_1, 0, wx.ALL | wx.EXPAND, 3)
        self.intro_pane.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.intro_pane, "Introduction")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def open_project(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'open_project' not implemented!")
        event.Skip()

    def load_image(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'load_image' not implemented!")
        event.Skip()

    def save_project(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'save_project' not implemented!")
        event.Skip()

    def save_project_as(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'save_project_as' not implemented!")
        event.Skip()

    def export_script(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'export_script' not implemented!")
        event.Skip()

    def exit(self, event):  # wxGlade: CVEFrame.<event_handler>
        print("Event handler 'exit' not implemented!")
        event.Skip()

# end of class CVEFrame
